OPENAI_API_KEY = "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"
GROQ_API_KEY = "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"
LANGCHAIN_API_KEY = "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"
LANGCHAIN_TRACING_V2 = "true"
GROQ_API_TRACING = "false"